import React from 'react';
import moment from 'moment';
import Head from 'next/head';
import { getPostDetails, getPosts } from '../../services';
import { useRouter } from 'next/router';
import {Navbar} from '../../components';
import { Content } from '.';
import styles from '../../styles/PostDetails.module.css';
import Image from 'next/image';
import { graphCMSImageLoader } from '../../util';

const PostDetails = ({ post }) => {

  const router = useRouter();
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <div class= {styles.post}>
        <div class = {styles.post_heading}>
          <h1>{post.title}</h1>
          <h2>{post.subheading}</h2>
        </div>
        <div class = {styles.post_image}>
          <Image
            loader={graphCMSImageLoader}
            alt={post.title}
            src={post.featuredImage.url}
            height= '100'
            width= '100'
          />
        </div>
        <div class = {styles.post_info}>
          <p>{moment(post.createdAt).format('MMM DD, YYYY')}</p>
          <p class = {styles.italic}>Written by {post.author}</p>
        </div>
        <Content post={post} />
      </div>
    </>
  )
}

export default PostDetails;

// Fetch data at build time
export async function getStaticProps({ params }) {
  const data = await getPostDetails(params.slug);
  return {
    props: {
      post: data,
    },
  };
}

// Specify dynamic routes to pre-render pages based on data.
// The HTML is generated at build time and will be reused on each request.
export async function getStaticPaths() {
  const posts = await getPosts();
  return {
    paths: posts.map(({ slug } ) => ({ params: { slug } })),
    fallback: true,
  };
}