import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import {Navbar} from '../components';
import {Header, WhatAI} from '../sections/landing';
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id = 'root'>
        <div class = {styles.gradient__bg}>
          <Navbar />
          <Header />
        </div>
        <WhatAI />
      </div>
    </>
  )
}
