import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Navbar } from '../components';
import { Header, WhatAI, Blog } from './landing';
import { getRecentPosts } from '../services';
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({posts}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id='root'>
        <div class={styles.gradient__bg}>
          <Navbar/>
          <Header />
        </div>
        <WhatAI />
        <Blog posts={posts} />
      </div>
    </>
  )
}

// Fetch data at build time
export async function getStaticProps() {
  const posts = (await getRecentPosts()) || [];
  return {
    props: { posts },
  };
}
